version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: husky
    versions:
    - 4.3.6
    - 4.3.8
  - dependency-name: swagger-jsdoc
    versions:
    - 6.0.0
    - 6.0.2
  - dependency-name: nodemailer
    versions:
    - 6.4.17
  - dependency-name: email-templates
    versions:
    - 8.0.2
  - dependency-name: supertest
    versions:
    - 6.0.1
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 99
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 99
