- name: "prio:critical"
  color: "FE0000"
- name: "prio:high"
  color: "FFC000"
- name: "prio:low"
  color: "01B0F1"
- name: "prio:medium"
  color: "FFFF02"
- name: "type:bug"
  color: "d73a4a"
- name: "type:build"
  color: "f9d0c4"
- name: "type:ci"
  color: "d3800c"
- name: "type:feat"
  color: "a2eeef"
- name: "type:layout"
  color: "b4d35f"
- name: "type:refactor"
  color: "c2e0c6"
- name: "type:pef"
  color: "bfdadc"
- name: "type:test"
  color: "f9f395"
- name: "type:usability"
  color: "bfd4f2"
- name: "wontfix"
  color: "ffffff"
