version: '2'

services:

  mongo:
    container_name: mongo
    image: sammlerio/mongo:latest@sha256:c8a1941d19da89eaa84b30276ec350e54f2e80bcd3bdd81f69a8f13070e8b333
    ports:
      - "27017:27017"

  auth-service:
    container_name: auth-service
    build:
      context: .
    environment:
      - NODE_ENV=development
      - PORT=3010
      - JWT_SECRET=foo
      - MONGODB_DEBUG=false
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
    ports:
      - "3010:3010"
    volumes:
      - ./coverage:/coverage
      - ./:/opt/auth-service
    command: npm run start:watch
    depends_on:
      - mongo
      - rabbitmq

  rabbitmq:
    container_name: rabbitmq
    image: sammlerio/rabbitmq:latest@sha256:7a295c01e08647990a8037be06c8dbd21824e688cdd2f3c56ff0a12f7353bcbe
    ports:
      - "15672:15672"
