version: '2'

services:

  mongo:
    image: sammlerio/mongo:3.7@sha256:82420e5a93ae7cc9ad22646388a01cfd58c230f0ba015a36d02dd3ed7c0324ac
    ports:
      - 27017:27017

  auth-service-test:
    image: sammlerio/auth-service-test
    environment:
      - NODE_ENV=test
      - PORT=3010
      - JWT_SECRET=foo
      - MONGODB_DEBUG=false
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
    depends_on:
      - mongo
    volumes:
      - ./coverage:/opt/auth-service/coverage
