version: '2'

services:

  mongo:
    image: sammlerio/mongo
    container_name: mongo
    ports:
      - 27017:27017

  auth-service-test:
    image: sammlerio/auth-service-test
    environment:
      - NODE_ENV=test
      - PORT=3010
      - JWT_SECRET=foo
      - MONGODB_DEBUG=false
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=sammlerio_test
    depends_on:
      - mongo
    volumes:
      - ./coverage:/opt/auth-service/coverage
