version: '2'

services:

  mongo:
    image: sammlerio/mongo
    container_name: mongo
    ports:
      - "27017:27017"

  auth-service:
    image: sammlerio/auth-service
    container_name: auth-service
    environment:
      - NODE_ENV=development
      - PORT=3010
      - JWT_SECRET=foo
      - MONGODB_DEBUG=false
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=sammlerio_dev
    ports:
      - "3010:3010"
    volumes:
      - ./coverage:/coverage
      - ./:/opt/auth-service
    command: npm run start:watch
    depends_on:
      - mongo
