version: '2'

services:

  mongo:
    image: sammlerio/mongo
    ports:
      - 27017:27017

  auth-service-test:
    image: sammlerio/auth-service-test
    environment:
      - PORT=3010
      - JWT_SECRET=foo
      - MONGODB_DEBUG=false
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - NODE_ENV=test
      - WINSTER_SUPRESS_LOGGING='true'
    links:
      - mongo
    volumes:
      - ./coverage:/opt/auth-service/coverage

  rabbitmq:
    image: sammlerio/rabbitmq

