version: '2'

services:

  mongo:
    image: sammlerio/mongo:3.7
    ports:
      - 27017:27017

  auth-service-test:
    image: sammlerio/auth-service-test
    environment:
      - PORT=3010
      - JWT_SECRET=foo
      - MONGODB_DEBUG=false
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
    links:
      - mongo
    volumes:
      - ./coverage:/opt/auth-service/coverage
