version: '2'

services:

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017

  auth-service-test:
    image: sammlerio/auth-service-test
    environment:
      - PORT=3010
      - JWT_SECRET=foo
      - AUDIT_LOG=false
      - MONGODB_DEBUG=false
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=sammlerio_integration
      - NODE_ENV=test
      - WINSTER_SUPRESS_LOGGING='true'
    depends_on:
      - mongo
    volumes:
      - ./coverage:/opt/auth-service/coverage

  rabbitmq:
    image: sammlerio/rabbitmq:latest@sha256:791b8cff36733be7ef12bde13c61e670888302220a8dd76b0d05336a5843b98c

