version: '2'

services:

  mongo:
    container_name: mongo
    image: sammlerio/mongo
    ports:
      - "27017:27017"

  auth-service:
    container_name: auth-service
    build:
      context: .
    environment:
      - NODE_ENV=development
      - PORT=3010
      - JWT_SECRET=foo
      - MONGODB_DEBUG=false
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
    ports:
      - "3010:3010"
    volumes:
      - ./coverage:/coverage
      - ./:/opt/auth-service
    command: npm run start:watch
    depends_on:
      - mongo
      - rabbitmq

  rabbitmq:
    container_name: rabbitmq
    image: sammlerio/rabbitmq
    ports:
      - "15672:15672"
